import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.tree.*;
import org.objectweb.asm.*;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;

public class ASMTransformer1 implements Opcodes {
    ClassNode cn;
    ClassReader cr;
    ClassWriter cw;

    /**
     * adds the method constructed by SpoonTransformers.constructMethod1
     * in the beginning of each method except constructors in a class
     *
     * @param fileIn
     * @param fileOut
     * @throws Exception
     */
    public void execute(String fileIn, String fileOut) throws Exception {
        readClass(fileIn);

        // add the method call to each method except constructors
        for (MethodNode mn : cn.methods) {
            if (mn.name.equals("<init>"))
                continue;
            InsnList il = new InsnList();
            il.add(new VarInsnNode(ALOAD, 0));
            il.add(new IntInsnNode(BIPUSH, 10));
            il.add(new IntInsnNode(BIPUSH, 10));
            il.add(new MethodInsnNode(INVOKEVIRTUAL, "Test", "method1", "(II)I", false));
            il.add(new InsnNode(POP));
            InsnList insns = mn.instructions;
            AbstractInsnNode in = insns.getFirst();
            insns.insertBefore(in, il);
        }

        // add the method code. generated by ASMifier
        MethodVisitor mv;
        cn.accept(cw);
        {
            mv = cw.visitMethod(ACC_PUBLIC, "method1", "(II)I", null, null);
            mv.visitCode();
            mv.visitVarInsn(ILOAD, 1);
            mv.visitVarInsn(ILOAD, 2);
            mv.visitInsn(IADD);
            mv.visitInsn(IRETURN);
            mv.visitMaxs(1, 3);
            mv.visitEnd();
        }
        cw.visitEnd();
        writeClass(fileOut);
    }

    private void readClass(String fileIn) throws Exception {
        FileInputStream is = new FileInputStream(fileIn);
        cn = new ClassNode();
        cr = new ClassReader(is);
        cr.accept(cn, 0);
        cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES);
    }

    private void writeClass(String fileOut) throws Exception {
        byte[] b = cw.toByteArray();
        new File(fileOut).getParentFile().mkdirs();
        FileOutputStream fos = new FileOutputStream(fileOut);
        fos.write(b);
        fos.close();
    }
}

